
import { OshiColor, Spot } from './types';

export const OSHI_COLORS: Record<OshiColor, { primary: string; secondary: string; text: string; hex: string }> = {
  pink: { primary: 'bg-pink-500', secondary: 'bg-pink-100', text: 'text-pink-600', hex: '#ec4899' },
  blue: { primary: 'bg-blue-500', secondary: 'bg-blue-100', text: 'text-blue-600', hex: '#3b82f6' },
  green: { primary: 'bg-emerald-500', secondary: 'bg-emerald-100', text: 'text-emerald-600', hex: '#10b981' },
  yellow: { primary: 'bg-amber-400', secondary: 'bg-amber-100', text: 'text-amber-700', hex: '#fbbf24' },
  purple: { primary: 'bg-purple-500', secondary: 'bg-purple-100', text: 'text-purple-600', hex: '#a855f7' },
  red: { primary: 'bg-rose-500', secondary: 'bg-rose-100', text: 'text-rose-600', hex: '#f43f5e' },
};

export const CATEGORY_LABELS: Record<string, string> = {
  artist: 'アーティスト',
  influencer: 'インフルエンサー',
  actor: '俳優',
  media: 'アニメ・映画・ゲーム',
  sports: 'スポーツ',
  other: 'その他'
};

export const PREFECTURES = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県',
  '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県',
  '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県',
  '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県'
];

export const CHECKIN_RADIUS_METERS = 200;

const timestamp = Date.now();

export const INITIAL_SPOTS: Spot[] = [
  // --- Artist: JO1 ---
  {
    id: 'jo1_1',
    name: '高松南新町商店街（MV撮影地）',
    category: 'artist',
    ipName: 'JO1',
    keywords: ['JO1', 'Your Key', '香川'],
    description: '『Your Key』MVの街並みシーンのロケ地として紹介されている商店街。',
    evidenceUrl: 'https://mqa.jp/jo1-yourkey-specialkeyvideo-filminglocation-where/',
    lat: 34.3412,
    lng: 134.0494,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'jo1_2',
    name: '荒崎オーシャンフロントハウス（MVロケ想定地）',
    category: 'artist',
    ipName: 'JO1',
    keywords: ['JO1', 'Your Key', '三浦'],
    description: '同MVの海辺の別荘シーンのロケ地としてファン調査で特定されている場所。',
    evidenceUrl: 'https://mqa.jp/jo1-yourkey-mv-filminglocation-where-miura/',
    lat: 35.1950,
    lng: 139.6050,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Artist: YOASOBI ---
  {
    id: 'yoa_1',
    name: '東京都庁前広場（ライブ・MV撮影エリア）',
    category: 'artist',
    ipName: 'YOASOBI',
    keywords: ['YOASOBI', '新宿'],
    description: 'YOASOBIのライブ映像・プロモーション撮影で大都市風景として登場。',
    evidenceUrl: 'https://realsound.jp/2021/01/post-699327.html',
    lat: 35.6895,
    lng: 139.6917,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'yoa_2',
    name: 'ラフォーレ原宿周辺（撮影協力エリア）',
    category: 'artist',
    ipName: 'YOASOBI',
    keywords: ['YOASOBI', '原宿'],
    description: 'プロモーション映像や関連ロケで背景として利用されるエリア。',
    evidenceUrl: 'https://natalie.mu/music/pp/yoasobi',
    lat: 35.6693,
    lng: 139.7058,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Artist: Snow Man ---
  {
    id: 'snw_1',
    name: '東京ソラマチ（施設内含む）',
    category: 'artist',
    ipName: 'Snow Man',
    keywords: ['Snow Man', 'スカイツリー'],
    description: 'Snow Man公式YouTube企画で登場する「謎解きロケ」などの撮影地。',
    evidenceUrl: 'https://officejr.jp/17214.html',
    lat: 35.7101,
    lng: 139.8113,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'snw_2',
    name: '浅草 飴細工 アメシン（ソラマチ内店舗）',
    category: 'artist',
    ipName: 'Snow Man',
    keywords: ['Snow Man', 'YouTube'],
    description: 'スカイツリー企画内でメンバーが訪れたとされる飴細工店（店舗の映像が確認可能）。',
    evidenceUrl: 'https://mom-eat.com/snowman-youtube-location-skytree/',
    lat: 35.7103,
    lng: 139.8115,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Media: 『君の名は。』 ---
  {
    id: 'kn_1',
    name: '飛騨古川 宮川朝市エリア',
    category: 'media',
    ipName: '『君の名は。』',
    keywords: ['君の名は。', '岐阜'],
    description: '「糸守町」のモデルとされる町並み巡りの拠点の一つ。',
    evidenceUrl: 'https://www.hida.jp/spot/detail_1007.html',
    lat: 36.2360,
    lng: 137.1860,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'kn_2',
    name: '古川祭屋台会館',
    category: 'media',
    ipName: '『君の名は。』',
    keywords: ['君の名は。', '岐阜'],
    description: '「君の名は。」巡礼者にもよく紹介される観光・展示施設。',
    evidenceUrl: 'https://www.hida.jp/spot/detail_1007.html',
    lat: 36.2362,
    lng: 137.1865,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Media: 『ぼっち・ざ・ろっく！』 ---
  {
    id: 'btr_1',
    name: '下北沢駅南口商店街',
    category: 'media',
    ipName: '『ぼっち・ざ・ろっく！』',
    keywords: ['ぼざろ', '下北沢'],
    description: '作中モデル地としてファンに最も認識されている商店街エリア。',
    evidenceUrl: 'https://www.timeout.jp/tokyo/ja/things-to-do/bocchi-the-rock-shimokitazawa',
    lat: 35.6617,
    lng: 139.6666,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'btr_2',
    name: 'シモキタエキウエ（駅上商業施設）',
    category: 'media',
    ipName: '『ぼっち・ざ・ろっく！』',
    keywords: ['ぼざろ', '下北沢'],
    description: '作品ファンが訪れる巡礼スポットとしてまとめサイトに掲載。',
    evidenceUrl: 'https://www.seichi-junrei.com/bocchi-the-rock',
    lat: 35.6620,
    lng: 139.6670,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Media: 『ラブライブ！サンシャイン!!』 ---
  {
    id: 'lls_1',
    name: '沼津港 港八十三番地',
    category: 'media',
    ipName: '『ラブライブ！サンシャイン!!』',
    keywords: ['ラブライブ', '沼津'],
    description: '「Aqoursの海の町」として公式観光でも紹介される代表的スポット。',
    evidenceUrl: 'https://numazukanko.jp/feature/lovelive',
    lat: 35.0811,
    lng: 138.8584,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'lls_2',
    name: '長浜海岸',
    category: 'media',
    ipName: '『ラブライブ！サンシャイン!!』',
    keywords: ['ラブライブ', '内浦'],
    description: '作中シーンの背景モデルとして多くのファンが訪れる海岸。',
    evidenceUrl: 'https://numazukanko.jp/feature/lovelive',
    lat: 35.0211,
    lng: 138.8924,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Influencer: コムドット ---
  {
    id: 'com_1',
    name: '原宿 竹下通り',
    category: 'influencer',
    ipName: 'コムドット',
    keywords: ['コムドット', '竹下通り'],
    description: 'コムドットひゅうがさんと人気インフルエンサー 加藤乃愛さんが原宿・竹下通りを満喫する動画が公開されており、訪問シーンが明示されている。',
    evidenceUrl: 'https://www.appbank.net/2022/09/10/youtubernews/2293939.php',
    lat: 35.6715,
    lng: 139.7042,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Influencer: きりたんぽ ---
  {
    id: 'kiri_1',
    name: '秋田駅前（秋田市）',
    category: 'influencer',
    ipName: 'きりたんぽ（YouTuber）',
    keywords: ['きりたんぽ', '秋田'],
    description: '「帰省」「街中Vlog」などで駅前エリアが頻出しており、投稿内で実際の地名・カットによって訪問が確認できる。',
    evidenceUrl: 'https://www.youtube.com/@kiritanpo',
    lat: 39.7167,
    lng: 140.1281,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Influencer: 希空 ---
  {
    id: 'noa_1',
    name: 'みなとみらい21（横浜）',
    category: 'influencer',
    ipName: '希空',
    keywords: ['希空', '横浜'],
    description: '投稿・インタビューで横浜みなとみらいエリアのカフェや施設が登場している。',
    evidenceUrl: 'https://mdpr.jp/influencer/detail/3892450',
    lat: 35.4542,
    lng: 139.6314,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'noa_2',
    name: '都内カフェ店舗（SNS投稿多数）',
    category: 'influencer',
    ipName: '希空',
    keywords: ['希空', 'カフェ'],
    description: '動画・投稿で実際に撮影・訪問したカフェが複数判明している（主に渋谷・原宿・表参道周辺）。',
    evidenceUrl: 'https://www.instagram.com/noa._.gram/',
    lat: 35.6690,
    lng: 139.7050,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Sports: 大谷翔平 ---
  {
    id: 'oht_1',
    name: '花巻東高校 2021記念モニュメント',
    category: 'sports',
    ipName: '大谷翔平',
    keywords: ['大谷翔平', '岩手'],
    description: '花巻東高校出身の大谷翔平選手を称える手形・記念モニュメントが設置され、観光協会のスポットとして紹介されている。',
    evidenceUrl: 'https://www.kanko-hanamaki.ne.jp/spot/article.php?p=535',
    lat: 39.4000,
    lng: 141.1340,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'oht_2',
    name: '奥州市伝統産業会館（握手像／展示）',
    category: 'sports',
    ipName: '大谷翔平',
    keywords: ['大谷翔平', '岩手'],
    description: '大谷翔平選手の3Dスキャン握手像や直筆グッズ展示があるスポットとして、公的な紹介がある。',
    evidenceUrl: 'https://www.city.oshu.iwate.jp/ohtani/knowabout/9600.html',
    lat: 39.1444,
    lng: 141.1736,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Sports: 三笘薫 ---
  {
    id: 'mit_1',
    name: '筑波大学（スポーツ棟／グラウンド）',
    category: 'sports',
    ipName: '三笘薫',
    keywords: ['三笘薫', '筑波'],
    description: '大学在籍期の活動拠点として知られ、チーム関係者・学生向けに現地で撮影されることがある。',
    evidenceUrl: 'https://en.wikipedia.org/wiki/Kaoru_Mitoma',
    lat: 36.1052,
    lng: 140.1022,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'mit_2',
    name: '等々力陸上競技場',
    category: 'sports',
    ipName: '三笘薫',
    keywords: ['三笘薫', '川崎'],
    description: '育成時代のクラブ拠点。クラブ公式ではないが、ファンが訪れる“ゆかりの地” として多数言及される。',
    evidenceUrl: 'https://en.wikipedia.org/wiki/Kaoru_Mitoma',
    lat: 35.5866,
    lng: 139.6517,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  // --- Sports: 羽生結弦 ---
  {
    id: 'han_1',
    name: 'アイスリンク仙台',
    category: 'sports',
    ipName: '羽生結弦',
    keywords: ['羽生結弦', '仙台'],
    description: '幼少期からの練習拠点として知られ、フィギュアスケートゆかりの施設。',
    evidenceUrl: 'https://visitjapan-vegetarian.com/a-guide-to-a-pilgrimage-to-hanyu-yuzurus-hometown-sendai/',
    lat: 38.3075,
    lng: 140.8817,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'han_2',
    name: '七北田公園（Nanakita Park）',
    category: 'sports',
    ipName: '羽生結弦',
    keywords: ['羽生結弦', '仙台'],
    description: '羽生選手ゆかりの地としてファンガイドなどで紹介される子ども時代の遊び・練習エリア。',
    evidenceUrl: 'https://visitjapan-vegetarian.com/a-guide-to-a-pilgrimage-to-hanyu-yuzurus-hometown-sendai/',
    lat: 38.3115,
    lng: 140.8845,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  }
];
