
import { OshiColor, Spot } from './types';

export const OSHI_COLORS: Record<OshiColor, { primary: string; secondary: string; text: string; hex: string }> = {
  pink: { primary: 'bg-pink-500', secondary: 'bg-pink-100', text: 'text-pink-600', hex: '#ec4899' },
  blue: { primary: 'bg-blue-500', secondary: 'bg-blue-100', text: 'text-blue-600', hex: '#3b82f6' },
  green: { primary: 'bg-emerald-500', secondary: 'bg-emerald-100', text: 'text-emerald-600', hex: '#10b981' },
  yellow: { primary: 'bg-amber-400', secondary: 'bg-amber-100', text: 'text-amber-700', hex: '#fbbf24' },
  purple: { primary: 'bg-purple-500', secondary: 'bg-purple-100', text: 'text-purple-600', hex: '#a855f7' },
  red: { primary: 'bg-rose-500', secondary: 'bg-rose-100', text: 'text-rose-600', hex: '#f43f5e' },
};

export const CATEGORY_LABELS: Record<string, string> = {
  artist: 'アーティスト',
  influencer: 'インフルエンサー',
  actor: '俳優',
  media: 'アニメ・映画・ゲーム',
  sports: 'スポーツ',
  other: 'その他'
};

export const PREFECTURES = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県',
  '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県',
  '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県',
  '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県'
];

export const CHECKIN_RADIUS_METERS = 200;

const timestamp = Date.now();

export const INITIAL_SPOTS: Spot[] = [
  {
    id: 'art_1',
    name: '平安神宮（ライブ会場）',
    category: 'artist',
    type: 'seichi',
    ipName: 'Aimer',
    address: '京都府京都市左京区岡崎西天王町97',
    keywords: ['平安神宮', '奉納ライブ', '京都'],
    description: 'Aimerが「Aimer Live in 平安神宮」など特別公演を開催した会場。神社境内での奉納ライブ形式が話題となり、ファンの巡礼スポットとして知られている。',
    evidenceUrl: 'https://www.aimer-web.jp/live/archive/?45537',
    lat: 35.0160,
    lng: 135.7824,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_2',
    name: '横浜アリーナ（ライブ会場）',
    category: 'artist',
    type: 'seichi',
    ipName: 'YOASOBI',
    address: '神奈川県横浜市港北区新横浜3-10',
    keywords: ['横浜アリーナ', 'YOASOBI', 'ライブ'],
    description: 'YOASOBIのアリーナ公演が開催された主要会場のひとつ。ライブツアーの節目公演地としてSNS投稿も多く、ファンの記念チェックイン先になっている。',
    evidenceUrl: 'https://www.yoasobi-music.jp/live/',
    lat: 35.5066,
    lng: 139.6200,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_1',
    name: '鷲宮神社',
    category: 'media',
    type: 'seichi',
    ipName: 'らき☆すた',
    address: '埼玉県久喜市鷲宮1-6-1',
    keywords: ['鷲宮神社', 'らき☆すた', '埼玉'],
    description: '作中に登場する神社のモデル地として広く知られる聖地。放送以降、絵馬奉納などファン巡礼文化が定着した代表例。',
    evidenceUrl: 'https://www.wasimiya.org/',
    lat: 36.0991,
    lng: 139.6644,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_2',
    name: '大洗磯前神社',
    category: 'media',
    type: 'seichi',
    ipName: 'ガールズ＆パンツァー',
    address: '茨城県東茨城郡大洗町磯浜町6890',
    keywords: ['大洗', 'ガルパン', '茨城'],
    description: '作品舞台となった大洗町の代表的スポット。作中背景に登場し、町ぐるみで巡礼を受け入れている。',
    evidenceUrl: 'https://www.oarai-info.jp/page/page000025.html',
    lat: 36.3155,
    lng: 140.5882,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_1',
    name: '日居城野運動公園（記念モニュメント）',
    category: 'sports',
    type: 'seichi',
    ipName: '大谷翔平',
    address: '岩手県花巻市松園町613-1',
    keywords: ['大谷翔平', '花巻', '岩手'],
    description: '花巻東高校ゆかりの地に設置された記念モニュメント。観光協会公式ページでも紹介されている。',
    evidenceUrl: 'https://www.kanko-hanamaki.ne.jp/spot/article.php?p=535',
    lat: 39.3875,
    lng: 141.1042,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_2',
    name: 'アイスリンク仙台',
    category: 'sports',
    type: 'seichi',
    ipName: '羽生結弦',
    address: '宮城県仙台市泉区泉中央2-18-1',
    keywords: ['羽生結弦', 'スケート', '仙台'],
    description: '羽生結弦選手が幼少期から練習したリンク。',
    evidenceUrl: 'https://icerink-sendai.net/',
    lat: 38.3188,
    lng: 140.8808,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'inf_1',
    name: '竹下通り',
    category: 'influencer',
    type: 'seichi',
    ipName: 'コムドット',
    address: '東京都渋谷区神宮前1丁目',
    keywords: ['コムドット', '原宿', 'ロケ地'],
    description: '原宿ロケ動画が複数投稿されており、メンバーゆかりの地としてファン訪問が多い。',
    evidenceUrl: 'https://www.youtube.com/@comdot',
    lat: 35.6715,
    lng: 139.7046,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_3',
    name: 'さいたまスーパーアリーナ',
    category: 'artist',
    type: 'seichi',
    ipName: '米津玄師',
    address: '埼玉県さいたま市中央区新都心8',
    keywords: ['米津玄師', 'ライブ', 'たまアリ'],
    description: '全国ツアー公演が開催された主要会場の一つ。',
    evidenceUrl: 'https://www.kenshiyonezu.jp/live/',
    lat: 35.8949,
    lng: 139.6309,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_4',
    name: '東京ドーム',
    category: 'artist',
    type: 'seichi',
    ipName: '嵐',
    address: '東京都文京区後楽1-3-61',
    keywords: ['嵐', 'ドーム', '東京'],
    description: '多数のドーム公演が行われた代表的会場。ファンにとって節目の場所。',
    evidenceUrl: 'https://www.johnnys-net.jp/',
    lat: 35.7056,
    lng: 139.7519,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_5',
    name: '大阪城ホール',
    category: 'artist',
    type: 'seichi',
    ipName: 'あいみょん',
    address: '大阪府大阪市中央区大阪城3-1',
    keywords: ['あいみょん', 'ライブ', '大阪'],
    description: '全国ツアー公演が行われた大型ホール会場。',
    evidenceUrl: 'https://www.aimyong.net/live/',
    lat: 34.6947,
    lng: 135.5298,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_3',
    name: '秩父神社',
    category: 'media',
    type: 'seichi',
    ipName: 'あの日見た花の名前を僕達はまだ知らない。',
    address: '埼玉県秩父市番場町1-3',
    keywords: ['あの花', '秩父', '埼玉'],
    description: '作品舞台のモデル地の一つ。秩父は公式に「聖地」として観光展開されている。',
    evidenceUrl: 'https://www.chichibu-jinja.or.jp/',
    lat: 35.9976,
    lng: 139.0847,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_4',
    name: '飛騨古川駅',
    category: 'media',
    type: 'seichi',
    ipName: '君の名は。',
    address: '岐阜県飛騨市古川町金森町8-1',
    keywords: ['君の名は。', '飛騨', '岐阜'],
    description: '作中背景のモデル地として観光協会が紹介している巡礼スポット。',
    evidenceUrl: 'https://www.hida-kankou.jp/spot/554',
    lat: 36.2361,
    lng: 137.1868,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_5',
    name: '鎌倉高校前駅',
    category: 'media',
    type: 'seichi',
    ipName: 'SLAM DUNK',
    address: '神奈川県鎌倉市腰越1-1-25',
    keywords: ['スラムダンク', '鎌倉', '神奈川'],
    description: 'オープニングシーンで有名な踏切がある駅。',
    evidenceUrl: 'https://www.kamakura-info.jp/',
    lat: 35.3067,
    lng: 139.5020,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_6',
    name: '人吉駅',
    category: 'media',
    type: 'seichi',
    ipName: '夏目友人帳',
    address: '熊本県人吉市中青井町326-1',
    keywords: ['夏目友人帳', '人吉', '熊本'],
    description: '熊本県人吉・球磨地方が作品背景モデルとされる地域。',
    evidenceUrl: 'https://hitoyoshionsen.net/',
    lat: 32.2155,
    lng: 130.7531,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_3',
    name: '等々力陸上競技場',
    category: 'sports',
    type: 'seichi',
    ipName: '三笘薫',
    address: '神奈川県川崎市中原区等々力1-1',
    keywords: ['三笘薫', 'フロンターレ', '川崎'],
    description: '川崎フロンターレ在籍時のホームスタジアム。',
    evidenceUrl: 'https://www.frontale.co.jp/',
    lat: 35.5866,
    lng: 139.6493,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_4',
    name: '松山中央公園野球場（坊っちゃんスタジアム）',
    category: 'sports',
    type: 'seichi',
    ipName: 'イチロー',
    address: '愛媛県松山市市坪西町625-1',
    keywords: ['イチロー', '松山', '愛媛'],
    description: '展示や関連イベント。',
    evidenceUrl: 'https://www.cul-spo.or.jp/centralpark/',
    lat: 33.8166,
    lng: 132.7441,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_5',
    name: '阪神甲子園球場',
    category: 'sports',
    type: 'seichi',
    ipName: 'ダルビッシュ有',
    address: '兵庫県西宮市甲子園町1-82',
    keywords: ['ダルビッシュ有', '甲子園', '兵庫'],
    description: '高校野球・プロ野球で活躍した舞台の一つ。',
    evidenceUrl: 'https://www.hanshin.co.jp/koshien/',
    lat: 34.7212,
    lng: 135.3616,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_7',
    name: '豊郷小学校旧校舎群',
    category: 'media',
    type: 'seichi',
    ipName: 'けいおん！',
    address: '滋賀県犬上郡豊郷町石畑518',
    keywords: ['けいおん', '豊郷', '滋賀'],
    description: '作中の学校モデル地として有名な聖地。',
    evidenceUrl: 'https://www.toyosato-elschool.com/',
    lat: 35.2031,
    lng: 136.2334,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_8',
    name: '伊勢志摩（鳥羽展望台周辺）',
    category: 'media',
    type: 'seichi',
    ipName: 'ラブライブ！サンシャイン!!',
    address: '三重県鳥羽市国崎町',
    keywords: ['ラブライブ', '鳥羽', '三重'],
    description: '作中に登場する背景のモデル地の一つ。',
    evidenceUrl: 'https://www.kanko-shima.com/',
    lat: 34.4072,
    lng: 136.9044,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_6',
    name: '京セラドーム大阪',
    category: 'artist',
    type: 'seichi',
    ipName: 'B\'z',
    address: '大阪府大阪市西区千代崎3-2-1',
    keywords: ['Bz', 'ドーム', '大阪'],
    description: 'ドームツアー開催実績多数。',
    evidenceUrl: 'https://bz-vermillion.com/live/',
    lat: 34.6692,
    lng: 135.4761,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_7',
    name: 'Zepp DiverCity（TOKYO）',
    category: 'artist',
    type: 'seichi',
    ipName: 'Aimer',
    address: '東京都江東区青海1-1-10',
    keywords: ['Aimer', 'Zepp', '東京'],
    description: 'ワンマンライブ開催会場。',
    evidenceUrl: 'https://www.aimer-web.jp/live/',
    lat: 35.6251,
    lng: 139.7755,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'art_8',
    name: '広島グリーンアリーナ',
    category: 'artist',
    type: 'seichi',
    ipName: 'ポルノグラフィティ',
    address: '広島県広島市中区基町4-1',
    keywords: ['ポルノグラフィティ', '広島', 'ライブ'],
    description: '凱旋公演地。',
    evidenceUrl: 'https://porno-graffitti.jp/live/',
    lat: 34.3995,
    lng: 132.4542,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_9',
    name: '岐阜県美濃加茂市（太田宿中山道会館）',
    category: 'media',
    type: 'seichi',
    ipName: '氷菓',
    address: '岐阜県美濃加茂市太田本町3-3-31',
    keywords: ['氷菓', '美濃加茂', '岐阜'],
    description: '作中背景モデル地。',
    evidenceUrl: 'https://www.city.minokamo.lg.jp/',
    lat: 35.4358,
    lng: 137.0183,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'ani_10',
    name: '宇治市（宇治橋）',
    category: 'media',
    type: 'seichi',
    ipName: '響け！ユーフォニアム',
    address: '京都府宇治市宇治',
    keywords: ['ユーフォ', '宇治', '京都'],
    description: '作中舞台として宇治市が公式に紹介。',
    evidenceUrl: 'https://www.city.uji.kyoto.jp/',
    lat: 34.8916,
    lng: 135.8078,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_6',
    name: '花巻東高等学校',
    category: 'sports',
    type: 'seichi',
    ipName: '大谷翔平',
    address: '岩手県花巻市松園町55-1',
    keywords: ['大谷翔平', '花巻東', '岩手'],
    description: '出身校。展示や訪問者多数。',
    evidenceUrl: 'https://www.hanamaki-higashi.ed.jp/',
    lat: 39.3828,
    lng: 141.0945,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'spo_7',
    name: '仙台市泉総合運動場',
    category: 'sports',
    type: 'seichi',
    ipName: '羽生結弦',
    address: '宮城県仙台市泉区野村字新桂島前60',
    keywords: ['羽生結弦', '仙台', 'スポーツ'],
    description: '仙台ゆかりのスケーターとして展示・イベント実績。',
    evidenceUrl: 'https://www.spf-sendai.jp/',
    lat: 38.3283,
    lng: 140.8931,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'inf_2',
    name: '渋谷スクランブル交さとく点',
    category: 'influencer',
    type: 'seichi',
    ipName: 'コムドット',
    address: '東京都渋谷区道玄坂2-2-1付近',
    keywords: ['コムドット', '渋谷', 'ロケ地'],
    description: '多数の街ロケ動画撮影地。',
    evidenceUrl: 'https://www.youtube.com/@comdot',
    lat: 35.6595,
    lng: 139.7005,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  },
  {
    id: 'inf_3',
    name: '浅草雷門',
    category: 'influencer',
    type: 'seichi',
    ipName: 'きりたんぽ',
    address: '東京都台東区浅草2-3-1',
    keywords: ['きりたんぽ', '浅草', 'ロケ地'],
    description: '街ロケ動画で頻出。',
    evidenceUrl: 'https://www.youtube.com/c/kiritanpo',
    lat: 35.7110,
    lng: 139.7964,
    isPublic: true,
    createdBy: 'system',
    createdAt: timestamp,
  }
];
